# BadCodecPlayer sdkconfig.defaults
# ESP32-C3 Super Mini / SSD1306 72x40 ビルトイン OLED

# FreeRTOS 1ms tick
CONFIG_FREERTOS_HZ=1000

# Flash 4MB
CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y
CONFIG_ESPTOOLPY_FLASHSIZE="4MB"

# ログレベル INFO
CONFIG_LOG_DEFAULT_LEVEL_INFO=y
CONFIG_LOG_DEFAULT_LEVEL=3

# メインタスク スタック
CONFIG_ESP_MAIN_TASK_STACK_SIZE=8192

# I2C
CONFIG_I2C_ENABLE_DEBUG_LOG=n
