[env:esp32-c3-mini]
platform    = espressif32
board       = esp32-c3-devkitm-1
framework   = espidf

; ビルドオプション
build_flags =
    -DCONFIG_FREERTOS_HZ=1000

; シリアルモニタ
monitor_speed  = 115200
monitor_filter = esp32_exception_decoder

; アップロード
upload_speed = 921600

; ESP-IDF のバージョンを固定したい場合はコメントを外す
; platform_packages =
;     platformio/framework-espidf @ ~5.1.0
