; ==============================================================
; BadCodecPlayer - ESP32-C3 Super Mini (OLED 72x40 ビルトイン)
; BadCodec v0.6.0 / Protocol 514 / SPEC rev.19
; ==============================================================

[env:esp32c3-supermini]
platform  = espressif32
board     = esp32-c3-devkitm-1
framework = espidf
board_build.partitions = partitions.csv
; シリアル 
monitor_speed  = 115200
monitor_filter = esp32_exception_decoder
upload_speed   = 921600
upload_port = /dev/tty.usbmodem14201 ;choice your own port

; ビルドフラグ
build_flags =
    -DCONFIG_FREERTOS_HZ=1000

