#!/usr/bin/env python3
"""
wave2adpcm4H.py — WAV ファイルを IMA-ADPCM C ヘッダに変換するツール

使い方:
    python3 wave2adpcm4H.py -i input.wav
    python3 wave2adpcm4H.py -i input.wav -o output.h

変換手順:
    1. 入力 WAV を IMA-ADPCM (adpcm_ima_wav) 形式に変換する。
       ffmpeg が必要な場合は自動的に呼び出す。
    2. 変換した WAV バイト列を C の uint8_t 配列として出力する。
    3. ヘッダ内にサンプルレート等のメタデータ定数を定義する。

ffmpeg が未インストールの場合:
    入力 WAV がすでに IMA-ADPCM 形式であればそのまま変換する。
    PCM WAV の場合は ffmpeg が必要。インストール方法:
        macOS:   brew install ffmpeg
        Ubuntu:  sudo apt install ffmpeg
        Windows: https://ffmpeg.org/download.html

出力ヘッダ内の定数:
    BAD_AUDIO_SIZE        … バイト数 (uint32_t)
    BAD_AUDIO_SAMPLE_RATE … サンプルレート Hz (uint32_t)
    BAD_AUDIO_CHANNELS    … チャンネル数 (uint32_t, 通常 1=mono)
    BAD_AUDIO_BLOCK_ALIGN … ブロックアライン (uint32_t)
    bad_audio_data[]      … WAV バイト列 (uint8_t[])
"""

import argparse
import os
import struct
import subprocess
import sys
import tempfile
from pathlib import Path


# ---------------------------------------------------------------------------
# WAV ヘッダ解析
# ---------------------------------------------------------------------------

WAV_FORMAT_PCM      = 0x0001
WAV_FORMAT_IMA_ADPCM = 0x0011


def _read_u16le(data: bytes, off: int) -> int:
    return struct.unpack_from("<H", data, off)[0]


def _read_u32le(data: bytes, off: int) -> int:
    return struct.unpack_from("<I", data, off)[0]


def parse_wav(data: bytes) -> dict:
    """WAV ヘッダを解析してメタデータを返す。"""
    if data[:4] != b"RIFF" or data[8:12] != b"WAVE":
        raise ValueError("RIFF/WAVE マジックが見つかりません")

    pos = 12
    info = {}
    while pos + 8 <= len(data):
        chunk_id = data[pos:pos+4]
        chunk_sz = _read_u32le(data, pos + 4)
        body_off = pos + 8

        if chunk_id == b"fmt ":
            fmt = _read_u16le(data, body_off + 0)
            ch  = _read_u16le(data, body_off + 2)
            sr  = _read_u32le(data, body_off + 4)
            ba  = _read_u16le(data, body_off + 12)
            info["audio_format"] = fmt
            info["channels"]     = ch
            info["sample_rate"]  = sr
            info["block_align"]  = ba

        elif chunk_id == b"data":
            info["data_offset"] = body_off
            info["data_size"]   = chunk_sz

        pos += 8 + chunk_sz
        if chunk_sz & 1:
            pos += 1  # RIFF pad byte

        if "audio_format" in info and "data_offset" in info:
            break

    if "audio_format" not in info:
        raise ValueError("fmt チャンクが見つかりません")
    if "data_offset" not in info:
        raise ValueError("data チャンクが見つかりません")

    return info


# ---------------------------------------------------------------------------
# ffmpeg による IMA-ADPCM 変換
# ---------------------------------------------------------------------------

DEFAULT_SAMPLE_RATE = 16000  # adpcm4.h と合わせる推奨値


def convert_to_ima_adpcm(input_path: str, sample_rate: int) -> bytes:
    """
    ffmpeg を使って入力 WAV を IMA-ADPCM (mono, sample_rate Hz) に変換し
    変換後の WAV バイト列を返す。
    """
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        tmp_path = tmp.name

    try:
        cmd = [
            "ffmpeg", "-y",
            "-i", input_path,
            "-ac", "1",                   # mono
            "-ar", str(sample_rate),      # サンプルレート
            "-c:a", "adpcm_ima_wav",      # IMA-ADPCM
            tmp_path
        ]
        result = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        if result.returncode != 0:
            err = result.stderr.decode(errors="replace")
            raise RuntimeError(
                f"ffmpeg 変換に失敗しました:\n{err}"
            )
        with open(tmp_path, "rb") as f:
            return f.read()
    finally:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)


# ---------------------------------------------------------------------------
# C ヘッダ生成
# ---------------------------------------------------------------------------

COLS = 16  # 1行に出力するバイト数


def generate_header(wav_bytes: bytes, meta: dict, guard_name: str) -> str:
    """WAV バイト列と解析済みメタ情報から C ヘッダ文字列を生成する。"""

    size        = len(wav_bytes)
    sample_rate = meta["sample_rate"]
    channels    = meta["channels"]
    block_align = meta["block_align"]

    lines = []
    lines.append(f"/**")
    lines.append(f" * @file  {guard_name.lower()}.h")
    lines.append(f" * @brief IMA-ADPCM audio data (auto-generated by wave2adpcm4H.py)")
    lines.append(f" *")
    lines.append(f" * Source   : (see -i argument)")
    lines.append(f" * Format   : IMA-ADPCM 4-bit, mono")
    lines.append(f" * SampleRate: {sample_rate} Hz")
    lines.append(f" * Channels  : {channels}")
    lines.append(f" * BlockAlign: {block_align} bytes")
    lines.append(f" * TotalSize : {size} bytes")
    lines.append(f" */")
    lines.append(f"")
    lines.append(f"#ifndef {guard_name}_H")
    lines.append(f"#define {guard_name}_H")
    lines.append(f"")
    lines.append(f"#include <stdint.h>")
    lines.append(f"")
    lines.append(f"/* ---- メタデータ定数 ---- */")
    lines.append(f"#define BAD_AUDIO_SIZE         {size}UL")
    lines.append(f"#define BAD_AUDIO_SAMPLE_RATE  {sample_rate}UL")
    lines.append(f"#define BAD_AUDIO_CHANNELS     {channels}UL")
    lines.append(f"#define BAD_AUDIO_BLOCK_ALIGN  {block_align}UL")
    lines.append(f"")
    lines.append(f"/* ---- WAV バイト列 ---- */")
    lines.append(f"const uint8_t bad_audio_data[] = {{")

    # バイト列を COLS 列で出力
    for i in range(0, size, COLS):
        chunk = wav_bytes[i:i + COLS]
        hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
        comma = "," if (i + COLS) < size else ""
        lines.append(f"    {hex_vals}{comma}")

    lines.append(f"}};")
    lines.append(f"")
    lines.append(f"#endif /* {guard_name}_H */")
    lines.append(f"")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# メイン
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="WAV ファイルを IMA-ADPCM C ヘッダ (adpcm4.h 互換) に変換する"
    )
    parser.add_argument(
        "-i", "--input",
        required=True,
        metavar="INPUT.WAV",
        help="入力 WAV ファイルパス"
    )
    parser.add_argument(
        "-o", "--output",
        metavar="OUTPUT.H",
        default=None,
        help="出力ヘッダファイルパス (省略時: 入力ファイル名.h)"
    )
    parser.add_argument(
        "-r", "--rate",
        type=int,
        default=DEFAULT_SAMPLE_RATE,
        metavar="HZ",
        help=f"出力サンプルレート Hz (デフォルト: {DEFAULT_SAMPLE_RATE})"
    )
    args = parser.parse_args()

    input_path = args.input
    if not os.path.isfile(input_path):
        print(f"エラー: 入力ファイルが見つかりません: {input_path}", file=sys.stderr)
        sys.exit(1)

    # 出力パスの決定
    if args.output:
        output_path = args.output
    else:
        stem = Path(input_path).stem
        output_path = str(Path(input_path).parent / (stem + ".h"))

    # ガード名 (ファイル名から生成、英数字とアンダースコアのみ)
    guard_name = Path(output_path).stem.upper()
    guard_name = "".join(c if c.isalnum() else "_" for c in guard_name)
    if guard_name and guard_name[0].isdigit():
        guard_name = "_" + guard_name

    # 入力 WAV を読み込んでフォーマット確認
    with open(input_path, "rb") as f:
        raw = f.read()

    try:
        meta_in = parse_wav(raw)
    except ValueError as e:
        print(f"エラー: WAV 解析失敗: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"入力: {input_path}")
    print(f"  フォーマット: 0x{meta_in['audio_format']:04X} "
          f"({'IMA-ADPCM' if meta_in['audio_format'] == WAV_FORMAT_IMA_ADPCM else 'PCM/Other'})")
    print(f"  サンプルレート: {meta_in['sample_rate']} Hz")
    print(f"  チャンネル: {meta_in['channels']}")
    print(f"  ブロックアライン: {meta_in['block_align']}")

    # IMA-ADPCM 変換が必要かどうか判定
    needs_convert = (
        meta_in["audio_format"] != WAV_FORMAT_IMA_ADPCM
        or meta_in["sample_rate"] != args.rate
        or meta_in["channels"] != 1
    )

    if needs_convert:
        print(f"\nffmpeg で IMA-ADPCM (mono, {args.rate}Hz) に変換中...")
        try:
            wav_bytes = convert_to_ima_adpcm(input_path, args.rate)
        except FileNotFoundError:
            print(
                "エラー: ffmpeg が見つかりません。\n"
                "インストール方法:\n"
                "  macOS:  brew install ffmpeg\n"
                "  Ubuntu: sudo apt install ffmpeg",
                file=sys.stderr
            )
            sys.exit(1)
        except RuntimeError as e:
            print(f"エラー: {e}", file=sys.stderr)
            sys.exit(1)

        meta = parse_wav(wav_bytes)
        print(f"  変換後 サンプルレート: {meta['sample_rate']} Hz")
        print(f"  変換後 ブロックアライン: {meta['block_align']}")
    else:
        print("\n入力はすでに IMA-ADPCM 形式です。変換をスキップします。")
        wav_bytes = raw
        meta = meta_in

    # ヘッダ生成
    header_text = generate_header(wav_bytes, meta, guard_name)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header_text)

    size_kb = len(wav_bytes) / 1024
    print(f"\n出力: {output_path}")
    print(f"  配列サイズ: {len(wav_bytes):,} bytes ({size_kb:.1f} KB)")
    print(f"  バッファ時間: {len(wav_bytes)*8 / meta['sample_rate'] / 4 / 1000:.1f} 秒 (概算)")
    print(f"  config.h の CFG_AUDIO_SR を {meta['sample_rate']} に設定してください。")


if __name__ == "__main__":
    main()
